/* tslint:disable */
/* eslint-disable */
/**
 * todo
 * Todo app api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTodoParam
 */
export interface CreateTodoParam {
    /**
     * 
     * @type {string}
     * @memberof CreateTodoParam
     */
    title: string;
}

export function CreateTodoParamFromJSON(json: any): CreateTodoParam {
    return CreateTodoParamFromJSONTyped(json, false);
}

export function CreateTodoParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTodoParam {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
    };
}

export function CreateTodoParamToJSON(value?: CreateTodoParam | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
    };
}


