/* tslint:disable */
/* eslint-disable */
/**
 * todo
 * Todo app api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ErrorsErrors,
    ErrorsErrorsFromJSON,
    ErrorsErrorsFromJSONTyped,
    ErrorsErrorsToJSON,
} from './';

/**
 * 
 * @export
 * @interface Errors
 */
export interface Errors {
    /**
     * 
     * @type {Array<ErrorsErrors>}
     * @memberof Errors
     */
    errors: Array<ErrorsErrors>;
}

export function ErrorsFromJSON(json: any): Errors {
    return ErrorsFromJSONTyped(json, false);
}

export function ErrorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Errors {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errors': ((json['errors'] as Array<any>).map(ErrorsErrorsFromJSON)),
    };
}

export function ErrorsToJSON(value?: Errors | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errors': ((value.errors as Array<any>).map(ErrorsErrorsToJSON)),
    };
}


