/* tslint:disable */
/* eslint-disable */
/**
 * todo
 * Todo app api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Todo,
    TodoFromJSON,
    TodoFromJSONTyped,
    TodoToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListTodo
 */
export interface ListTodo {
    /**
     * 
     * @type {Array<Todo>}
     * @memberof ListTodo
     */
    list: Array<Todo>;
}

export function ListTodoFromJSON(json: any): ListTodo {
    return ListTodoFromJSONTyped(json, false);
}

export function ListTodoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTodo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'list': ((json['list'] as Array<any>).map(TodoFromJSON)),
    };
}

export function ListTodoToJSON(value?: ListTodo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'list': ((value.list as Array<any>).map(TodoToJSON)),
    };
}


