/* tslint:disable */
/* eslint-disable */
/**
 * todo
 * Todo app api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTodoParam
 */
export interface UpdateTodoParam {
    /**
     * 
     * @type {string}
     * @memberof UpdateTodoParam
     */
    title?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTodoParam
     */
    completed?: boolean;
}

export function UpdateTodoParamFromJSON(json: any): UpdateTodoParam {
    return UpdateTodoParamFromJSONTyped(json, false);
}

export function UpdateTodoParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTodoParam {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'completed': !exists(json, 'completed') ? undefined : json['completed'],
    };
}

export function UpdateTodoParamToJSON(value?: UpdateTodoParam | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'completed': value.completed,
    };
}


